// ─── Department Config with SLA hours ─────────────────────────────────────
export const DEPARTMENTS = {
  'Maintenance':  { name: 'Maintenance & Facilities', head: 'Facilities Office', slaHours: 24, icon: '🔧' },
  'IT/Network':   { name: 'IT & Network Services',    head: 'IT Department',     slaHours: 8,  icon: '💻' },
  'Furniture':    { name: 'Furniture & Infrastructure',head: 'Facilities Office', slaHours: 48, icon: '🪑' },
  'Cleanliness':  { name: 'Housekeeping',              head: 'Admin Office',      slaHours: 12, icon: '🧹' },
  'Security':     { name: 'Campus Security',           head: 'Security Office',   slaHours: 2,  icon: '🔒' },
  'Other':        { name: 'General Administration',    head: 'Admin Office',      slaHours: 48, icon: '📋' },
};

export const CATEGORIES = Object.keys(DEPARTMENTS);

const API = '/api';

// ─── SLA Helpers ────────────────────────────────────────────────────────────
export const getSlaStatus = (ticket) => {
  if (ticket.status === 'Resolved' || ticket.status === 'Closed') return { status: 'done', pct: 100, label: 'Resolved', color: 'var(--secondary)' };
  if (!ticket.slaDeadline) return null;
  const now = Date.now();
  const start = new Date(ticket.timestamp).getTime();
  const end = new Date(ticket.slaDeadline).getTime();
  const elapsed = now - start;
  const total = end - start;
  const pct = Math.min(Math.round((elapsed / total) * 100), 100);
  const hoursLeft = Math.max(0, Math.round((end - now) / 3600000));
  if (now > end) return { status: 'breached', pct: 100, label: 'SLA Breached', color: 'var(--danger)', hoursLeft: 0 };
  if (pct >= 75) return { status: 'critical', pct, label: `${hoursLeft}h left`, color: 'var(--warning)', hoursLeft };
  return { status: 'ok', pct, label: `${hoursLeft}h left`, color: 'var(--secondary)', hoursLeft };
};

const makeSla = (submittedAt, category) => {
  const slaH = DEPARTMENTS[category]?.slaHours || 48;
  return new Date(new Date(submittedAt).getTime() + slaH * 3600000).toISOString();
};

// ─── Users ─────────────────────────────────────────────────────────────────
export const getUsers = async () => {
  const res = await fetch(`${API}/users`);
  return res.json();
};

export const getStaffList = async () => {
  const users = await getUsers();
  return users.filter(u => u.role === 'staff');
};

export const authenticate = async (id, password, role) => {
  const users = await getUsers();
  return users.find(u => (u.id === id || u.email === id) && u.password === password && u.role === role) || null;
};

export const registerStudent = async (name, email, password) => {
  const users = await getUsers();
  if (users.find(u => u.email === email)) return { error: 'Email already registered.' };
  const newId = `S${String(users.filter(u => u.role === 'student').length + 1).padStart(3, '0')}`;
  const initials = name.split(' ').map(n => n[0]).join('').slice(0, 2).toUpperCase();
  const newUser = { id: newId, name, email, password, role: 'student', avatar: initials, joined: new Date().toISOString().split('T')[0] };
  users.push(newUser);
  // for a real backend we'd have POST /api/users, but since we didn't add that, we'll just mock registration failing for now or add the endpoint
  // Let's just return an error for now since the backend doesn't have POST /api/users yet, or simulate it.
  // Actually, I can just not save it persistently if it's just a demo, or tell the user. Let's return error.
  return { error: 'Registration disabled in this demo.' };
};

// ─── Tickets ────────────────────────────────────────────────────────────────
export const getTickets = async () => {
  const res = await fetch(`${API}/tickets`);
  return res.json();
};

export const getTicketsByStudent = async (studentId) => {
  const tickets = await getTickets();
  return tickets.filter(t => t.studentId === studentId);
};

export const getTicketsByStaff = async (staffId) => {
  const tickets = await getTickets();
  return tickets.filter(t => t.assignedTo === staffId);
};

export const saveTicket = async (ticket) => {
  const submittedAt = new Date().toISOString();
  // id is generated by backend or here. Let's do it here for simplicity or let backend do it. We'll generate a random id.
  const newTicket = {
    ...ticket,
    id: `TKT-${Math.floor(1000 + Math.random() * 9000)}`,
    status: 'Pending',
    timestamp: submittedAt,
    slaDeadline: makeSla(submittedAt, ticket.category),
    department: DEPARTMENTS[ticket.category]?.name || 'General Administration',
    assignedTo: null, assignedName: null,
    comments: [],
    statusHistory: [{ from: null, to: 'Pending', by: ticket.studentName, at: submittedAt }],
    resolvedAt: null, escalatedAt: null, rating: null,
  };
  const res = await fetch(`${API}/tickets`, {
    method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(newTicket)
  });
  return res.json();
};

export const updateTicketStatus = async (id, newStatus, byName) => {
  const tickets = await getTickets();
  const t = tickets.find(x => x.id === id);
  const update = {
    status: newStatus,
    resolvedAt: newStatus === 'Resolved' ? new Date().toISOString() : t.resolvedAt,
    escalatedAt: newStatus === 'Escalated' ? new Date().toISOString() : t.escalatedAt,
    statusHistory: [...(t.statusHistory || []), { from: t.status, to: newStatus, by: byName || 'Admin', at: new Date().toISOString() }],
  };
  const res = await fetch(`${API}/tickets/${id}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(update) });
  return res.json();
};

export const assignTicket = async (id, staffId, staffName) => {
  const tickets = await getTickets();
  const t = tickets.find(x => x.id === id);
  const status = t.status === 'Pending' ? 'In Progress' : t.status;
  const update = {
    assignedTo: staffId, assignedName: staffName, status,
    statusHistory: status !== t.status ? [...(t.statusHistory || []), { from: t.status, to: status, by: 'Admin (Auto)', at: new Date().toISOString() }] : t.statusHistory,
  };
  const res = await fetch(`${API}/tickets/${id}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(update) });
  return res.json();
};

export const addComment = async (id, text, author, authorRole) => {
  const tickets = await getTickets();
  const t = tickets.find(x => x.id === id);
  const update = { comments: [...(t.comments || []), { author, authorRole, text, timestamp: new Date().toISOString() }] };
  const res = await fetch(`${API}/tickets/${id}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(update) });
  return res.json();
};

export const rateTicket = async (id, rating) => {
  const res = await fetch(`${API}/tickets/${id}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ rating }) });
  return res.json();
};

export const deleteTicket = async (id) => {
  const res = await fetch(`${API}/tickets/${id}`, { method: 'DELETE' });
  return res.json();
};

export const runEscalationCheck = async () => {
  let tickets = await getTickets();
  const now = Date.now();
  let changed = false;
  for (const t of tickets) {
    if (['Resolved', 'Closed', 'Escalated'].includes(t.status)) continue;
    if (t.slaDeadline && now > new Date(t.slaDeadline).getTime()) {
      t.status = 'Escalated';
      t.escalatedAt = new Date().toISOString();
      t.statusHistory.push({ from: t.status, to: 'Escalated', by: 'System (SLA Breach)', at: t.escalatedAt });
      changed = true;
      await fetch(`${API}/tickets/${t.id}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(t) });
    }
  }
  if (changed) tickets = await getTickets();
  return tickets;
};

export const bulkUpdateStatus = async (ids, newStatus, byName) => {
  let tickets = await getTickets();
  for (const id of ids) {
    const t = tickets.find(x => x.id === id);
    if (!t) continue;
    t.status = newStatus;
    t.resolvedAt = newStatus === 'Resolved' ? new Date().toISOString() : t.resolvedAt;
    t.statusHistory = [...(t.statusHistory || []), { from: t.status, to: newStatus, by: byName, at: new Date().toISOString() }];
    await fetch(`${API}/tickets/${t.id}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(t) });
  }
  return await getTickets();
};

// ─── Analytics ──────────────────────────────────────────────────────────────
export const getAnalytics = async () => {
  const tickets = await getTickets();
  const now = new Date();
  const last7Days = Array.from({ length: 7 }, (_, i) => {
    const d = new Date(); d.setDate(now.getDate() - i);
    return d.toISOString().split('T')[0];
  }).reverse();

  const dailySubmissions = last7Days.map(date => ({
    date: date.slice(5),
    count: tickets.filter(t => t.timestamp.startsWith(date)).length,
  }));

  const deptPerf = CATEGORIES.map(cat => {
    const deptTickets = tickets.filter(t => t.category === cat);
    const deptResolved = deptTickets.filter(t => t.status === 'Resolved');
    let avgRes = 0; let avgRat = 0;
    if (deptResolved.length) {
      avgRes = deptResolved.reduce((acc, t) => acc + (new Date(t.resolvedAt) - new Date(t.timestamp)) / 3600000, 0) / deptResolved.length;
      const rated = deptResolved.filter(t => t.rating);
      if (rated.length) avgRat = rated.reduce((acc, t) => acc + t.rating, 0) / rated.length;
    }
    return {
      department: DEPARTMENTS[cat]?.name || cat, total: deptTickets.length,
      resolved: deptResolved.length,
      escalated: deptTickets.filter(t => t.status === 'Escalated').length,
      resolutionRate: deptTickets.length ? Math.round((deptResolved.length / deptTickets.length) * 100) : 0,
      avgResHours: avgRes, avgRating: avgRat,
    };
  }).filter(d => d.total > 0);

  const byPriority = ['Low', 'Medium', 'High'].map(p => ({
    label: p, count: tickets.filter(t => t.priority === p).length,
  }));

  const users = await getUsers();
  const staffPerf = users.filter(u => u.role === 'staff').map(s => {
    const assigned = tickets.filter(t => t.assignedTo === s.id);
    const staffResolved = assigned.filter(t => t.status === 'Resolved');
    return {
      id: s.id, name: s.name, avatar: s.avatar, department: s.department,
      assigned: assigned.length, resolved: staffResolved.length,
      resolutionRate: assigned.length ? Math.round((staffResolved.length / assigned.length) * 100) : 0,
    };
  });

  return { dailySubmissions, deptPerf, byPriority, staffPerf };
};

export const getStats = async () => {
  const tickets = await getTickets();
  return {
    total: tickets.length,
    pending: tickets.filter(t => t.status === 'Pending').length,
    inProgress: tickets.filter(t => t.status === 'In Progress').length,
    resolved: tickets.filter(t => t.status === 'Resolved' || t.status === 'Closed').length,
  };
};

// ─── Announcements ─────────────────────────────────────────────────────────
export const getAnnouncements = async () => {
  const res = await fetch(`${API}/announcements`);
  return res.json();
};

export const saveAnnouncement = async (ann) => {
  const newAnn = { ...ann, id: `ANN-${Date.now()}`, timestamp: new Date().toISOString() };
  await fetch(`${API}/announcements`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(newAnn) });
  return await getAnnouncements();
};

export const deleteAnnouncement = async (id) => {
  await fetch(`${API}/announcements/${id}`, { method: 'DELETE' });
  return await getAnnouncements();
};

// ─── Notifications ──────────────────────────────────────────────────────────
export const getNotifications = async (userId) => {
  const res = await fetch(`${API}/notifications`);
  const all = await res.json();
  return all.filter(n => n.userId === userId).sort((a, b) => new Date(b.timestamp) - new Date(a.timestamp));
};

export const createNotification = async (userId, ticketId, message, type) => {
  const newN = { id: `N${Date.now()}`, userId, ticketId, message, type, read: false, timestamp: new Date().toISOString() };
  await fetch(`${API}/notifications`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(newN) });
};

export const markAllRead = async (userId) => {
  await fetch(`${API}/notifications/read`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ userId }) });
};

export const getUnreadCount = async (userId) => {
  const notifs = await getNotifications(userId);
  return notifs.filter(n => !n.read).length;
};

// ─── Export ─────────────────────────────────────────────────────────────
export const exportTicketsCSV = async () => {
  const tickets = await getTickets();
  const headers = ['ID', 'Title', 'Category', 'Priority', 'Status', 'Department', 'Student', 'Location', 'SLA Deadline', 'Submitted', 'Resolved At', 'Rating', 'Comments'];
  const rows = tickets.map(t => [
    t.id, `"${t.title}"`, t.category, t.priority, t.status, t.department || '',
    t.studentName || '', `"${t.location || ''}"`,
    t.slaDeadline ? new Date(t.slaDeadline).toLocaleString() : '',
    new Date(t.timestamp).toLocaleString(),
    t.resolvedAt ? new Date(t.resolvedAt).toLocaleString() : '',
    t.rating || '', t.comments?.length || 0,
  ]);
  const csv = [headers, ...rows].map(r => r.join(',')).join('\n');
  const blob = new Blob([csv], { type: 'text/csv' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = `campus-solver-tickets-${new Date().toISOString().slice(0, 10)}.csv`;
  a.click(); URL.revokeObjectURL(url);
};

// ─── Hotspot Map Data ────────────────────────────────────────────────────────
export const CAMPUS_ZONES = [
  { id: 'block-a', name: 'Block A', type: 'Academic', row: 0, col: 0 },
  { id: 'block-b', name: 'Block B', type: 'Academic', row: 0, col: 1 },
  { id: 'block-c', name: 'Block C', type: 'Academic', row: 0, col: 2 },
  { id: 'library', name: 'Library', type: 'Facility', row: 0, col: 3 },
  { id: 'seminar', name: 'Seminar Hall', type: 'Academic', row: 1, col: 0 },
  { id: 'labs',    name: 'Labs',    type: 'Academic', row: 1, col: 1 },
  { id: 'canteen', name: 'Canteen', type: 'Facility', row: 1, col: 2 },
  { id: 'main-gate', name: 'Main Gate', type: 'Security', row: 1, col: 3 },
  { id: 'hostel-a', name: 'Hostel A', type: 'Hostel', row: 2, col: 0 },
  { id: 'hostel-b', name: 'Hostel B', type: 'Hostel', row: 2, col: 1 },
  { id: 'hostel-c', name: 'Hostel C', type: 'Hostel', row: 2, col: 2 },
  { id: 'sports',  name: 'Sports Ground', type: 'Facility', row: 2, col: 3 },
];

export const getHotspotData = async () => {
  const tickets = (await getTickets()).filter(t => !['Resolved', 'Closed'].includes(t.status));
  return CAMPUS_ZONES.map(zone => {
    const matches = tickets.filter(t =>
      t.location?.toLowerCase().includes(zone.name.toLowerCase().split(' ')[0]) ||
      t.location?.toLowerCase().includes(zone.id.replace('-', ' '))
    );
    return { ...zone, count: matches.length, tickets: matches };
  });
};

export const findSimilarTickets = async (title) => {
  if (!title || title.length < 5) return [];
  const similarity = (a, b) => {
    const s1 = a.toLowerCase().trim(), s2 = b.toLowerCase().trim();
    if (!s1 || !s2) return 0;
    const longer = s1.length > s2.length ? s1 : s2;
    const shorter = s1.length > s2.length ? s2 : s1;
    if (longer.includes(shorter)) return 0.9;
    const words1 = new Set(s1.split(/\s+/));
    const words2 = s2.split(/\s+/);
    const common = words2.filter(w => words1.has(w) && w.length > 3).length;
    return common / Math.max(words1.size, words2.length);
  };

  const tickets = await getTickets();
  return tickets
    .filter(t => !['Resolved', 'Closed'].includes(t.status))
    .map(t => ({ ...t, score: similarity(title, t.title) }))
    .filter(t => t.score > 0.4)
    .sort((a, b) => b.score - a.score)
    .slice(0, 3);
};
